name: smartbrains-web CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}        

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: smartbrains-web-artifact
        path: build/libs
    - name: Deploy to AWS Elasticbeanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: smartbrains-web
        environment_name: SmartbrainsWeb-env
        version_label: ${{ steps.buildnumber.outputs.build_number }}
        region: us-east-1
        deployment_package: build/libs/smartbrains-web.jar
